Update README.md and docs.
TheJacksonLaboratory/ClintLR pull request #99
Opened 2024-01-17 16:51 UTC by mabeckwith

2024-01-17 17:48 UTC, pnrobinson commented on docs/developers.md
This looks incorrect --- To complete setup, download the LIRICAL resources and compile.
I thought that the pom file does this now automatically?

2024-01-17 17:48 UTC, pnrobinson requested changes
Please see my comment in the developers.md file.

2024-01-17 17:56 UTC, ielis commented on README.md
> +![Screenshot of the ClintLR interface](docs/_static/ClintLR_screenshot_and_results.png "ClintLR (CLinical INTuition with Likelihood Ratios). (A) Users can download input files and adjust settings via
... ClintLR the**n** runs ...

2024-01-17 21:27 UTC, mabeckwith commented on docs/developers.md
That used to be automatic by using Jitpack in the pom file, but that was removed when testing LIRICAL versions that weren't tagged (e.g. snapshots). I could put Jitpack back since LIRICAL v2.0.0 works and is tagged.

2024-01-19 20:25 UTC, mabeckwith commented on docs/developers.md
The new JARS include LIRICAL, so it no longer needs to be installed separately. The docs have been changed. See new PR #102.

2024-01-20 06:22 UTC, merged